### ISSUE TITLE
[feature request] Trades with empty result / request should render differently

### ISSUE THREAD

**Issue by Yarden-zamir** [mortuusars/Wares#12]
Currently if a trade doesn't return anything (returns air) and I assume the other way around as well. The ui still displays as if it's a regular trade. While it's not critical I would love to have a different visual that represents the fact that it's an a trade without reward 
<img width="317" alt="Screen Shot 2023-11-18 at 15 24 48" src="https://github.com/mortuusars/Wares/assets/8178413/9fe04efc-3dc0-4d46-84fd-0f25a965d6cc">

**Comment by mortuusars** [comment]
You can set payment or requested item to an empty array so that it will not render the slot box.
![image](https://github.com/mortuusars/Wares/assets/65141267/8b0cf6b3-6912-4e2f-b1d7-4970c5913cd3)
It's not really different, but a bit cleaner imo. 

I probably could change it to something better, but the code for rendendering agreements is quite convoluted, so I don't want to touch it lol.

**Comment by Yarden-zamir** [comment]
This is great, thank you!
